default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: reviews_site_development


test:
  <<: *default
  database: reviews_site_test


production:
  <<: *default
  database: reviews_site_production
  username: reviews_site
  password: <%= ENV['REVIEWS_SITE_DATABASE_PASSWORD'] %>
